# LiveKit Agent Configuration
api_key: ${LIVEKIT_API_KEY}
api_secret: ${LIVEKIT_API_SECRET}
ws_url: ${LIVEKIT_URL}

# Agent dispatch configuration
agent:
  # Accept jobs for all rooms (for testing)
  # In production, use specific room patterns
  job_request_timeout: 10s
  worker_type: "process"
  
  # Room patterns to accept
  room_patterns:
    - "*"  # Accept all rooms for testing
  
  # Metadata to match (optional)
  # metadata:
  #   agent_name: "polyglot-flight-agent"