# LiveKit Agent Configuration

# Agent metadata
agent_id = "polyglot-flight-assistant"
agent_name = "Polyglot Flight Assistant"
subdomain = "polyglot-rag-assistant-3l6xagej"

[agent]
# Entry point for the agent
entrypoint = "agent.py"

# Runtime configuration
[agent.runtime]
type = "python"
python_version = "3.11"

# Worker configuration
[agent.worker]
type = "process"
num_processes = 1